### ISSUE TITLE
Check for ARIA Landmarks

### ISSUE THREAD

**Issue by Heydon** [karlgroves/diagnostic.css#12]
Some examples:

Checking for role="main" / <main> on #main...

``` css
#main:not([role="main"]):not(main):after {
   content: 'error message';
}
```

Checking for role="banner" on page-level header:

``` css
body > header:not([role="banner"]), 
#header:not([role="banner"]), 
#page-header:not([role="banner"]) {
   content: 'error message';
}
```

You could do the same for contentinfo on the page footer, maybe?
